/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucr.ac.cr.spesv2.Vista.PanelesMenuPrincipal;

import javax.swing.ImageIcon;
import ucr.ac.cr.spesv2.Controlador.Controlador;
import ucr.ac.cr.spesv2.Vista.PanelPadre;
import ucr.ac.cr.spesv2.Vista.animaciones.AnimacionBotonEventos;
import ucr.ac.cr.spesv2.Vista.animaciones.AnimacionBotonProducciones;
import ucr.ac.cr.spesv2.Vista.animaciones.AnimacionBotonUsuario;
import ucr.ac.cr.spesv2.Vista.render.RenderEscala;


/**
 *
 * @author Emmanuel Méndez R
 */
public class PanelNavegador extends PanelPadre {
    
    /**
     * Creates new form PanelNavegador
     */
    private RenderEscala render;
    
    public PanelNavegador(){
        render = new RenderEscala(1920);
        initComponents();
        //Animaciones
        AnimacionBotonUsuario  botonUsuarioA = new AnimacionBotonUsuario(linea,this);
        AnimacionBotonEventos botonEventosA = new AnimacionBotonEventos(linea,this);
        AnimacionBotonProducciones botonProduccionesA = new AnimacionBotonProducciones(linea,this);
        //asigacion
        btnUsuarios.addMouseListener(botonUsuarioA);
        btnEventos.addMouseListener(botonEventosA);
        btnProducciones.addMouseListener(botonProduccionesA);
        
        
        
    }//Fin PanelNavegador
    

    public void cambiarBotones(String estado){
        switch(estado){
            case "Producciones":
                btnProducciones.setIcon(new ImageIcon());
                btnEventos.setIcon(new ImageIcon());
                btnUsuarios.setIcon(new ImageIcon());
            break;
            
            case "Eventos":
                btnProducciones.setIcon(new ImageIcon());
                btnEventos.setIcon(new ImageIcon());
                btnUsuarios.setIcon(new ImageIcon());
            break;
            
            case "Usuarios":
                btnProducciones.setIcon(new ImageIcon());
                btnEventos.setIcon(new ImageIcon());
                btnUsuarios.setIcon(new ImageIcon());
            break;
        }//Fin switch
    }//Fin cambiarBotones
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        btnProducciones = new javax.swing.JButton();
        btnEventos = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        linea = new javax.swing.JLabel();

        setBackground(new java.awt.Color(241, 241, 241));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProducciones.setIcon(render.escalarImageIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonProducciones.png"))));
        btnProducciones.setActionCommand("Producciones");
        btnProducciones.setBorder(null);
        btnProducciones.setBorderPainted(false);
        btnProducciones.setContentAreaFilled(false);
        add(btnProducciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        remove(btnProducciones);
        add(btnProducciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(render.escalarCordenada(10), render.escalarCordenada(20), -1, -1));

        btnEventos.setBackground(new java.awt.Color(255, 255, 255));
        btnEventos.setIcon(render.escalarImageIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonEventos.png"))));
        btnEventos.setActionCommand("Eventos");
        btnEventos.setBorder(null);
        btnEventos.setBorderPainted(false);
        btnEventos.setContentAreaFilled(false);
        add(btnEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));
        remove(btnEventos);
        add(btnEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(render.escalarCordenada(480), render.escalarCordenada(20), -1, -1));

        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setIcon(render.escalarImageIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonUsuarios.png"))));
        btnUsuarios.setActionCommand("usuario");
        btnUsuarios.setBorder(null);
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setContentAreaFilled(false);
        add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, -1));
        remove(btnUsuarios);
        add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(render.escalarCordenada(780), render.escalarCordenada(20), -1, -1));

        btnPerfil.setBackground(new java.awt.Color(255, 255, 255));
        btnPerfil.setIcon(render.escalarImageIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fotoPerfil.png"))));
        btnPerfil.setActionCommand("PefilUsuario");
        btnPerfil.setBorder(null);
        btnPerfil.setBorderPainted(false);
        btnPerfil.setContentAreaFilled(false);
        add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, -1, -1));
        remove(btnPerfil);
        add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(render.escalarCordenada(1100), render.escalarCordenada(10), -1, -1));

        linea.setIcon(render.escalarImageIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linea.png"))));
        add(linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        remove(linea);
        add(linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(render.escalarCordenada(12),render.escalarCordenada(75), -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEventos;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnProducciones;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel linea;
    // End of variables declaration//GEN-END:variables

    @Override
    public void escuchar(Controlador controlador) {
        btnEventos.addActionListener(controlador);
        btnPerfil.addActionListener(controlador);
        btnProducciones.addActionListener(controlador);
        btnUsuarios.addActionListener(controlador);
        
    }
}
